apiVersion: v1
kind: Pod
metadata: 
    name: pytorch-ddik-pod-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-3090
  containers:
  - name: gpu-container
    image:  gitlab-registry.nrp-nautilus.io/udembys/iksolver
    command: ["/bin/bash", "-c"]
    args: ["cd /home;
            git clone https://github.com/jacketdembys/kanets.git;
            pip install ipykernel;
            pip install ipywidgets;
            pip install imageio; 
            sudo apt-get update;
            sudo apt-get install -y libgl1-mesa-glx libgtk2.0-0;
            sudo rm -rf /var/lib/apt/lists/;
            pip install opencv-python;
            sleep infinity"]
    resources:
      limits:
        memory: 16Gi
        cpu: 16
        nvidia.com/gpu: 1
      requests:
        memory: 16Gi
        cpu: 16
        nvidia.com/gpu: 1